const positiveComments = [
    "Keep it up!",
    "Kudos to you!",
    "Worth sharing!",
    "Amazing!",
    "Inspiring!",
    "Love this!",
    "Congratulations!",
    "What an achievement!",
    "Happy for you!",
    "Impressive!",
    "Well done!",
    "Wonderful!",
    "You are amazing as always!",
    "Fantastic work!",
    "Absolutely brilliant!",
    "You're doing great!",
    "So proud of you!",
    "You're a rock star!",
    "This is pure gold!",
    "You've got this!",
    "Keep shining!",
    "Your efforts are paying off!",
    "This is incredible!",
    "You inspire me!",
    "Such a positive impact!",
    "Your creativity is unmatched!",
    "You are a true gem!",
    "This is what success looks like!",
    "Every step counts, and you're nailing it!",
    "Your hard work is truly commendable!",
    "You're a trailblazer!",
    "This is a game changer!",
    "Your enthusiasm is contagious!",
    "You've set the bar high!",
    "You're a beacon of positivity!",
    "Keep pushing the limits!",
    "Your passion shines through!",
    "You make a difference!",
    "Your talent is evident!",
    "Bravo for your achievement!",
    "You've outdone yourself!",
    "This is remarkable!",
    "Your journey is inspiring!",
    "You have a bright future ahead!",
    "Keep the momentum going!",
    "Your dedication is admirable!",
    "This is just the beginning!",
    "You are capable of amazing things!"
];

export default positiveComments;
